# Generated by Django 6.0.4 on 2026-04-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitienda', '0002_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
