# Generated by Django 6.0.4 on 2026-05-08 17:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_validation_token_and_delivered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='validation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token de validación'),
        ),
    ]
